      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_OCEAN_0B86FE110 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./src/Cloud5mins.ShortenerTools.TinyBlazorAdmin"
          output_location: "wwwroot"
          skip_deploy_on_missing_secrets: true  # Adiciona essa linha para ignorar a falta de token
